# Exploratory data analysis on raw TPM data

RNA-seq data was collected and ...

## Data extraction

We'll apply our data loading pipeline to the our Fcnts and CFU filepaths.

Number of samples          : 480
Number of features (genes) : 2191

,F01-SP0085-SP0086,F02-SP0103-SP0104,F03-SP0115-SP0116,F04-SP0116-SP0117,F05-SP0117-SP0118,F06-SP0129-SP0130,F07-SP0239-SP0240,F08-SP0256-SP0257,F09-SP0257-SP0258,F10-SP0311-SP0312,...,SP_2231,SP_2233,SP_2234,SP_2235,SP_2236,SP_2237,SP_2238,SP_2239,SP_2240,CFU
Labels,,,,,,,,,,,,,,,,,,,,,
NDC1hr-a,17.873518,2466.545463,494.725485,32.828910,1429.881428,16.932806,2276.344255,363.428196,263.813123,1879.541509,...,64.521089,6.283659,29.032123,13.244918,22.321678,2.553360,18.096937,1232.456175,1609.040485,580000000
NDC1hr-b,8.599118,2848.027779,461.431900,25.270876,1792.237161,32.586130,1828.204870,366.895688,383.864614,2118.098463,...,65.478593,4.030836,25.084719,17.266754,20.077578,0.000000,28.377088,1234.082514,1664.082222,1000000000
NDC1hr-c,6.976092,2288.158311,559.140388,41.002339,1462.776430,8.811906,2061.237871,288.345153,411.868496,1868.124115,...,64.530904,5.232069,26.825195,17.342955,21.212371,11.959016,28.253174,1369.580457,1827.791359,800000000
14CEF1hr-a,2.366695,2718.858963,323.120819,20.865554,628.793434,5.979018,4015.700532,485.961328,201.074389,893.863250,...,35.642257,3.328165,19.456585,12.898958,10.794698,16.228764,21.300253,1958.037472,1537.434864,340000000
14CEF1hr-b,14.497379,2493.549214,295.418292,15.976704,860.686510,0.000000,1878.367974,604.057465,151.352638,819.483432,...,42.827745,2.038694,15.378435,12.129281,14.956572,0.000000,24.464327,1769.710527,1570.874119,700000000

Separate data into sample x gene matrix and CFU values.

In [24]:
# Columns of data matrix
cols = data_df.columns
rna_data = data_df[[col for col in cols if col != "CFU"]]
cfu_data = data_df[[col for col in cols if col == "CFU"]]

## Data annotation

Define function to help convert condition labels to drug and timepoint.

Apply and add labels to data for visualization.

In [30]:
# Add columns for each metadata aspect
drug_labels = [condition_to_drug(cond) for cond in rna_data.index]
time_labels = [condition_to_time(cond) for cond in rna_data.index]

## PCA

In [ ]:
# Create scaler and PCA
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import seaborn as sns

# Initialize scaler for data centering
scaler = StandardScaler(with_std = False)

# Make new centered df
transformed_data = rna_data.copy()
transformed_data = scaler.fit_transform(transformed_data)

# PCA object
pca = PCA(n_components = 2)

# Make PCA transformed df
transformed_data = pca.fit_transform(transformed_data)

# Find percent variance


transformed_df = pd.DataFrame({"PC1": transformed_data[:,0],
                               "PC2": transformed_data[:,1]
                               })
transformed_df["Drug"] = drug_labels
transformed_df["Timepoint"] = time_labels

# Plot  
sns.scatterplot(transformed_data, x = "0", y = "1", )

ValueError: Could not interpret value `0` for `x`. An entry with this name does not appear in `data`.

In [ ]:
sns.scatterplot()

                0             1
0     3765.207376 -18914.191045
1     1420.212335 -23111.902624
2     6877.352154 -16834.751446
3   -12294.813154 -26806.164225
4    -6394.988625 -20869.966724
..            ...           ...
475 -21505.399341  40233.231510
476 -22607.922734  35304.625596
477 -15481.815668  19508.234618
478 -10100.366421  21889.755280
479 -10710.173162  14535.659987

[480 rows x 2 columns]

## Heatmap

## Feature correlation

## CFU across timepoint?